export const sendOtpConstant = {
    OTP_SEND_FAILURE:'OTP_SEND_FAILURE',
    OTP_SEND_SUCCESS:'OTP_SEND_SUCCESS',
    OTP_SEND_REQUIEST:'OTP_SEND_REQUIEST'
}

export const verIfyOtpConstant = {
    OTP_VERIFICATION_FAILURE:'OTP_VERIFICATION_FAILURE',
    OTP_VERIFICATION_SUCCESS:'OTP_VERIFICATION_SUCCESS',
    OTP_VERIFICATION_REQUIEST:'OTP_VERIFICATION_REQUIEST'
}

export const accountActivationConstant = {
    SET_NAME_FAILURE:'SET_NAME_FAILURE',
    SET_NAME_SUCCESS:'SET_NAME_SUCCESS',
    SET_NAME_REQUIEST:'SET_NAME_REQUIEST'
}


export const avatarConstant = {
    SET_AVATAR_FAILURE:'SET_AVATAR_FAILURE',
    SET_AVATAR_SUCCESS:'SET_AVATAR_SUCCESS',
    SET_AVATAR_REQUIEST:'SET_AVATAR_REQUIEST'
}


export const autoLoginConstant = {
    AUTO_AUTH_FAILURE:'AUTO_AUTH_FAILURE',
    AUTO_AUTH_SUCCESS:'AUTO_AUTH_SUCCESS',
    AUTO_AUTH_REQUIEST:'AUTO_AUTH_REQUIEST'
}


export const logoutConstatnt = {
    USER_LOGOUT_FAILURE:'USER_LOGOUT_FAILURE',
    USER_LOGOUT_SUCCESS:'USER_LOGOUT_SUCCESS',
    USER_LOGOUT_REQUIEST:'USER_LOGOUT_REQUIEST'
}