export const sendOtpConstant = {
    OTP_SEND_FAILURE:'OTP_SEND_FAILURE',
    OTP_SEND_SUCCESS:'OTP_SEND_SUCCESS',
    OTP_SEND_REQUIEST:'OTP_SEND_REQUIEST'
}

export const verIfyOtpConstant = {
    OTP_VERIFICATION_FAILURE:'OTP_VERIFICATION_FAILURE',
    OTP_VERIFICATION_SUCCESS:'OTP_VERIFICATION_SUCCESS',
    OTP_VERIFICATION_REQUIEST:'OTP_VERIFICATION_REQUIEST'
}


export const authConstant = {
    AUTH_FAILURE:'AUTH_FAILURE',
    AUTH_SUCCESS:'AUTH_SUCCESS',
    AUTH_REQUIEST:'AUTH_REQUIEST'
}